photoalbum_proj/Login/urls.py
from django.urls import path
from . import views

app_name = 'Login'
urlpatterns = [
    path('login_user/', views.login_user, name="login"),
    path('captcha/', views.captcha, name ='captcha')
    
]

photoalbum_proj/organizer_app/urls.py
from django.urls import path
from .import views 

app_name = 'organizer_app'
urlpatterns = [
    path('', views.index, name="home"),
    path('pokemon/', views.pokemon, name="pokemon"),
]

photoalbum_proj/photoalbum_proj/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

from . import views 
app_name = 'projects'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha', include('captcha.urls')),
    path('org/', include('organizer_app.urls')),
    path('login/', include('Login.urls')),
    path('login/', include('django.contrib.auth.urls')),
    path('qrc/', views.qrc_view, name='qrc')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photoalbum_proj/Login/models.py
from django.db import models

# Create your models here.

photoalbum_proj/organizer_app/models.py
from django.db import models
import qrcode
from io import BytesIO
from django.core.files import File 
from PIL import Image, ImageDraw
# Create your models here.

class Website(models.Model):
    name = models.URLField()
    qr_code = models.ImageField(upload_to='qr_codes', blank=True)

    def __str__(self):
        return str(self.name)
    
    def save(self, *args, **kwargs):
        qrcode_img = qrcode.make(self.name)
        canvas = Image.new('RGB', (290, 290), 'white')
        canvas.paste(qrcode_img)
        fname = f'qr_code-{self.id}.png'
        buffer = BytesIO()
        canvas.save(buffer,'PNG')
        # # print(dir(self.qr_code))
        # print(File(buffer))
        # print(dir(File(buffer)))
        self.qr_code.save(fname, File(buffer), save=False)
        canvas.close()
        super().save(*args, **kwargs)

photoalbum_proj/Login/forms.py
from django import forms 
from captcha.fields import CaptchaField


class MyForm(forms.Form):
    captcha = CaptchaField()

photoalbum_proj/organizer_app/forms.py
from django import forms 
# from captcha.fields import CaptchaField 

# class MyForm(forms.Form):
#     captcha = CaptchaField()

class Directory(forms.Form):
    path = forms.CharField(label="Enter directory path")

photoalbum_proj/Login/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages 
from .forms import MyForm
# Create your views here.

# def login_user(request):
#     if request.method == "POST":
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             # print('goes to captcha')
#             login(request, user)
#             form = MyForm()
#             return HttpResponseRedirect(reverse('Login:captcha'))
        
#         form = MyForm(request.POST)
#         if form.is_valid():
#             messages.success(request, "Success!")
#             return render(request, 'organizer_app\poke.html',{})
#         else:
#             messages.error(request, "Wrong Captcha")
#         form = MyForm()
#         # login(request, user)
#         return render(request,'authentication/captcha.html', {'form': form})
#         # redirect to a success page.
#     else: 
#         print('returns to login')
#         # return an 'invalid login' error
#         messages.success(request, ("Unsuccessful login attempt, please try again..."))
#         return render(request,'authentication/login.html')
    
    # else:
    #     print('go to authentication html')
    #     return render(request, 'authentication/login.html', {})


def captcha(request):
    if request.method == "POST":
        form = MyForm(request.POST)
        if form.is_valid():
            messages.success(request, "Success!")
            return render(request, 'organizer_app\poke.html',{})
        else:
            messages.error(request, "Wrong Captcha")
    form = MyForm()
    return render(request, 'authentication/captcha.html', {'form': form})



def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            # print('goes to captcha')
            login(request, user)
            form = MyForm()
            return HttpResponseRedirect(reverse('Login:captcha'))
        if request.method == 'POST':
            form = MyForm(request.POST)
            if form.is_valid():
                messages.success(request, "Success!")
                return render(request, 'organizer_app\poke.html',{})
            else:
                messages.error(request, "Wrong Captcha")
            form = MyForm()
            # login(request, user)
            return render(request,'authentication/captcha.html', {'form': form})
            # redirect to a success page.
        else: 
            print('returns to login')
            # return an 'invalid login' error
            messages.success(request, ("Unsuccessful login attempt, please try again..."))
            return render(request,'authentication/login.html')
    
    else:
        print('go to authentication html')
        return render(request, 'authentication/login.html', {})

photoalbum_proj/organizer_app/views.py
from fileinput import filename
from django.shortcuts import render
from .models import Website
from .forms import *
from multiprocessing import context
# from django.contrib import messages

def index(request):
    return render(request, 'organizer_app/index.html')

def pokemon(request):
    return render(request, 'organizer_app\poke.html' )

photoalbum_proj/photoalbum_proj/views.py
from django.shortcuts import render
from organizer_app.models import Website



def qrc_view(request):
    name = "Welcome to "

    obj = Website.objects.get(id=2)
    context = {
        'name': name,
        'obj': obj,
    }

    return render(request, 'organizer_app\home.html', context)

photoalbum_proj/Login/templates/authentication/captcha.html
{% extends 'organizer_app/base.html' %}

{% block content %}
    <section>

    
    
        <div class="container">
        <div class="captcha">
        <h1 class="text-center mt-3 text-info">Django Captcha Authentication</h1>
            {% if messages %}
            {% for message in messages %}
            <div class="alert text-center mt-5 alert-{{message.tags}}">
                {{message}}
            </div>
            {% endfor %}
            {% endif %}
            <form action ="" method="post" class="text-center mt-5">
                {% csrf_token %}
                {{form.captcha}}
                <input type="submit" value="Submit" class="btn btn-primary">
            </form>
        </div>
     </div>
    </section>

    <style>
        @import url(https://fonts.googleapis.com/css?family=Roboto:300);
      h1{
        font-size: large;
        color:black;
        text-decoration:solid;
        
      }
      div.captcha
      {    
        max-width: 360;
        z-index: 1;
        text-align: center;
        
        position: absolute;
        width: 300px;
        height: 300px;
        display: grid;
        /* justify-content: center; */
        margin-left: 300px;
        margin-top: -100px;
        margin-bottom: 100px;
        box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
      }
      img.captcha {
        position: absolute;
        max-width: auto;
        top: 50%;
        left:50%;
        transform: translate(-50%,-50%);
        border: 1px solid transparent;
        border-image: linear-gradient(45deg, #ff0, #f0f, #f00, #00f, #0f0);
        border-image-slice:1;
        margin: auto;
        padding: 15px;
        text-align: center;
        border-image: auto;
        
      }
      .captcha {
        font-family: "Roboto", sans-serif;
        outline: 0;
        background: #f2f2f2;
        width: auto;
        border: 0;
        margin: 0 0 15px;
        padding: 15px;
        box-sizing: border-box;
        font-size: 14px;
        justify-content: center;
        align-items: center;
        display: grid;
        
      }
      form.text-center.mt5
      {
        margin: 15px 0 0;
        color: #b3b3b3;
        font-size: 12px;
      }
      
      body {
        background-color: #133ed6f5;
        background-image: linear-gradient(45deg,#1b47e8d1,yellow );
        font-family: "Roboto", sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        justify-items: center;

      }
      input.btn.btn-primary
      {
        background-color: #133ed6f5;
        color: white
      }
      </style>
{% endblock %}

photoalbum_proj/Login/templates/authentication/login.html
{% extends 'organizer_app/base.html' %}

{% block content %}
<section>


  <div class="login-page">
    <div class="form">
      <div class="login">
        <div class="login-header">
          <h3>LOGIN</h3>
          <p>Please enter your credentials to login.</p>
        </div>
      </div>

    <form action="{% url 'Login:login' %}" method=POST>
        {% csrf_token %}
        <form>
            <div class="login-form">
              <input type="text" class="form-control" name="username" placeholder="username"/>
              
            </div>
            <div class="mb-3">
              <input type="text" class="form-control" name="password" placeholder="password"/>
            </div>
            <input type="submit" value="Login" class="btn btn-secondary">
            <p class="message">Not registered? <a href="#">Create an account</a></p>
        </form>
    
    </form> 
</section>
<style>
  @import url(https://fonts.googleapis.com/css?family=Roboto:300);
header .header{
  background-color: #fff;
  height: 45px;
}
header a img{
  width: 134px;
margin-top: 4px;
}
.login-page {
  width: 360px;
  padding: 8% 0 0;
  margin: auto;
}
.login-page .form .login{
  margin-top: -31px;
margin-bottom: 26px;
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 100px;
  padding: 45px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form input {
  font-family: "Roboto", sans-serif;
  outline: 0;
  background: #f2f2f2;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  padding: 15px;
  box-sizing: border-box;
  font-size: 14px;
}
.form button {
  font-family: "Roboto", sans-serif;
  text-transform: uppercase;
  outline: 0;
  background-color: #133ed6f5;
  background-image: linear-gradient(45deg,#1b47e8d1,yellow );
  width: 100%;
  border: 0;
  padding: 15px;
  color: #FFFFFF;
  font-size: 14px;
  -webkit-transition: all 0.3 ease;
  transition: all 0.3 ease;
  cursor: pointer;
}
.form .message {
  margin: 15px 0 0;
  color: #b3b3b3;
  font-size: 12px;
}
.form .message a {
  color: #133ed6f5;
  text-decoration: none;
}

.container {
  position: relative;
  z-index: 1;
  max-width: 300px;
  margin: 0 auto;
}

body {
  background-color: #133ed6f5;
  background-image: linear-gradient(45deg,#1b47e8d1,yellow );
  font-family: "Roboto", sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
input.btn.btn-secondary
{
  background-color: #133ed6f5;
  color: white
}
</style>
{% endblock %}

photoalbum_proj/organizer_app/templates/organizer_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">    <title> -->
    <link rel="stylesheet" href="{% static 'css\style.css' %}">  
      {% block title%}
      {% endblock title %}
    </title>
</head>
<body>
        <header>
            <a href="#" class="logo">Pokemon TCG Deck Builder</a>
            <div class="toggle"></div>
            <ul class="navigation">
                <li><a href="{% url 'organizer_app:home'%}"style="--i:1;" class="active">Home</a></li>
                <li><a href="{% url 'Login:login' %}" style="--i:2;">Login</a></li>
                <li><a href="{%url 'logout' %}"style="--i:3;">Logout</a></li>
                <li><a href="#"style="--i:4;">Signup</a></li>

            </ul>
        </header>
        <script>
            const menuToggle = document.querySelector('.toggle');
            const navigation = document.querySelector('.navigation');
            menuToggle.onclick = function(){
                menuToggle.classList.toggle('active');
                navigation.classList.toggle('active');
            }
        </script>



    {% block content %}
    {% endblock content %}
        
</body>
</html>

photoalbum_proj/organizer_app/templates/organizer_app/home.html
{% extends 'organizer_app/base.html' %}


{% block content %}

<body>
    <div class="ui-container">
    
      <h1> {{name}} - {{obj.name}} </h1>
        <img src = {{obj.qr_code.url}}>
    </div>
    
    
    
</body>
</html>

{% endblock%}

photoalbum_proj/organizer_app/templates/organizer_app/index.html
{% extends 'organizer_app/base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css\index.css' %}">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<body> 
    
    <section>
        <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmir-s3-cdn-cf.behance.net%2Fproject_modules%2Fdisp%2F5d108a54697949.56094ee6014bc.jpg&f=1&nofb=1" class="pokemonWC">
        <div class="content">
            <div class="textBox">
                <h2>Start Building Your Virtual Inventory Today</h2>
                <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. 
                    Dolore distinctio veritatis deserunt eaque quam voluptates libero nam pariatur obcaecati explicabo.
                </p>
                <a href="#">Learn How</a> 
            </div>
        </div>

        <ul class="sci">
            <li><a href ="#" style="--i:12;"><i class="fa fa-facebook"></i></a></li>
            <li><a href ="#" style="--i:13;"><i class="fa fa-twitter"></i></a></li>
            <li><a href ="#" style="--i:14;"><i class="fa fa-instagram"></i></a></li>
        </ul>


    </section> 
    </div>

</body>

{% endblock%}

photoalbum_proj/organizer_app/templates/organizer_app/poke.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Pokemon HTML</title>
    <!-- Bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script> 
    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <!-- load static js -->
    <script  defer src="{% static 'js\main.js' %}"></script>

</head>
  <body>
      <style>
          body{
              background-color: aliceblue;
              background-image: url("https://assets.pokemon.com/assets/cms2/img/misc/virtual-backgrounds/pokemon/detective-pikachu.jpg");
          }
        
          .poke-card{
              width: 215px;
              height: 300px;
              margin: 20px 10px;
              background: none;
              
              cursor: pointer;
              font-size: 2rem;
              transition: 100ms;
              border-radius: 15px;
              box-shadow: -3px -3px 3px 0 rgba(#26e6f7, 0.3), -3px -3px 3px 0 rgba(#f759e4, 0.3) 0px 0px 6px 2 rgba(#ffe759, 0.3), 0px 35px 25px -15px rgba(0, 0, 0, 0.3);
              position: relative;
              overflow: hidden;
              display: inline-block;
              vertical-align: middle;
          }
          .poke-card:hover{
              transform: scale(1.2);
              outline: auto;
              
          }
          .pokeball{
            position: relative;
            float: left;
            background-image: url('http://bit.ly/pokeballimg');
            background-size: 100% 100%;
            width: 40px;
            height: 40px;
            position: relative;
            display: grid;
            justify-content: right;
            vertical-align: middle;
            background-color: rgb(0, 119, 255);
            border-radius: 20%;
            cursor: pointer;
            -webkit-transition-duration: 0.4s; /* Safari */
            transition-duration: 0.4s;
          }
          .pokeball:hover {
                box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
                background-color: black;
                color: white;
                }
          h1{
              image-resolution: auto;
              background-image: none;
            }

      </style>
      
    <h1><img src="https://fontmeme.com/permalink/220608/4f3f73dc02c6baa6768f5695dc4f17c6.png"></h1>
    <form class="row gy-2 gx-3 align-items-center">
        <div class="col-auto">
          <label class="sr-only" for="search">.</label>
          <input type="text" class="form-control mb-2" id="search" placeholder="Gotta catch'em all">
        </div>

        <div class="col-auto">
            <button id="savedCards"> </button>
        </div>
        
        <div class="col-auto">
          <button type="submit" class="pokeball" id="submit-button">.</button>
        </div>
      </form>
    

    <!-- <input type="text" name="card-name" id="search"> -->


      <!-- bootstrap grid -->
      <div class="container">
          <div class="row" id="card-container">

          </div>
      </div>

    
  </body>
</html>